{
    "name": "Bill.com Integration",
    "summary": "Integration with Bill.com API v3 for vendor and bill synchronization",
    "author": "Binhex, Simple Solutions, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/l10n-usa",
    "license": "AGPL-3",
    "category": "Accounting",
    "version": "16.0.1.0.0",
    "depends": [
        "base",
        "web",
        "l10n_us",
        "l10n_us_account_routing",
        "contacts",
    ],
    "external_dependencies": {
        "python": ["requests"],
    },
    "assets": {
        "web.assets_backend": [
            "billcom/static/src/scss/billcom_dashboard.scss",
        ],
    },
    "data": [
        "data/ir_cron_data.xml",
        "data/billcom_status_data.xml",
        "security/billcom_security.xml",
        "security/ir.model.access.csv",
        "wizards/billcom_mfa_wizard_views.xml",
        "wizards/billcom_partner_matching_wizard_views.xml",
        "wizards/billcom_sync_wizard.xml",
        "views/account_move_views.xml",
        "views/account_payment_register_views.xml",
        "views/account_payment_report.xml",
        "views/account_payment_views.xml",
        "views/account_tax_views.xml",
        "views/billcom_config_kanban_dashboard.xml",
        "views/billcom_config_views.xml",
        "views/billcom_document_views.xml",
        "views/billcom_from_billcom_actions.xml",
        "views/billcom_funding_account_views.xml",
        "views/billcom_item_views.xml",
        "views/billcom_logger_views.xml",
        "views/billcom_payment_purpose_views.xml",
        "views/billcom_sync_queue_views.xml",
        "views/billcom_webhook_log_views.xml",
        "views/res_partner_bank_views.xml",
        "views/res_partner_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
