[metadata]
name = odoo-addons-l10n-usa-l10n_us_sales_tax_engine
version = 18.0.1.0.0
description = Hybrid USA Sales Tax Engine for Odoo 18
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://github.com/OCA/l10n-usa
author = Odoo Community Association (OCA)
author_email = support@odoo-community.org
license = LGPL-3
classifiers =
    Programming Language :: Python
    Framework :: Odoo
    Framework :: Odoo :: 18.0

[options]
packages = find_namespace:
install_requires =
    requests

[options.extras_require]
test =
    pytest
    odoo>=18.0,<19.0
