from . import account_payment
from . import res_bank
from . import res_config_settings
from . import res_partner_bank
from . import res_partner
from . import res_user
from . import res_company
from . import account_move
from . import sale_order
from . import payment_provider
