[project]
name = "odoo-addons-oca-l10n-usa"
version = "18.0.20260724.0"
dependencies = [
    "odoo-addon-account_banking_ach_base==18.0.*",
    "odoo-addon-account_banking_ach_credit_transfer==18.0.*",
    "odoo-addon-account_banking_ach_direct_debit==18.0.*",
    "odoo-addon-l10n_us_account_routing==18.0.*",
    "odoo-addon-l10n_us_base_county==18.0.*",
    "odoo-addon-l10n_us_crm_county==18.0.*",
    "odoo-addon-l10n_us_form_1099==18.0.*",
    "odoo-addon-l10n_us_gaap==18.0.*",
    "odoo-addon-l10n_us_gaap_mis_report==18.0.*",
    "odoo-addon-l10n_us_mis_financial_report==18.0.*",
    "odoo-addon-l10n_us_partner_legal_number==18.0.*",
    "odoo-addon-l10n_us_sales_tax_engine==18.0.*",
    "odoo-addon-l10n_us_sales_tax_provider_api_ninjas==18.0.*",
    "odoo-addon-l10n_us_sales_tax_provider_ziptax==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
